name: Unit & Integration Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
            NEXT_PUBLIC_BACKEND_API_URL: http://localhost:3333
            NEXT_PUBLIC_APP_URL: http://localhost:3000
            BETTER_AUTH_URL: http://localhost:3333
            BETTER_AUTH_SECRET: kdsajflkajksdjfklajsdkjfalksjdklfa

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: npm install -g pnpm && pnpm install --no-frozen-lockfile

            - name: Approve builds
              run: pnpm approve-builds --all

            - name: Run tests
              run: pnpm test
